#' @title Two-dimensional tri-objective problem based on Branin and Currin functions.
#' @param x Vector or matrix to evaluate at, takes values in [0,1]^3
#' @param params List of additional parameters:
#' \itemize{
#' \item \code{A} and \code{B} embedding matrices of size 3x3
#' \item \code{seed} random seed for reproducibility
#' }
#'
#' @note Problem generated by sampling 2 random matrices and extracting an orthonormal basis from them.
#'
#' @export
problem_synthetic <- function(x, params = list(A = NULL, B = NULL, seed = 19)) {
  A <- params$A
  B <- params$B
  seed <- params$seed


  if (is.null(A) || is.null(B)) {
    if (exists(".Random.seed", .GlobalEnv)) {
      oldseed <- .GlobalEnv$.Random.seed
    } else {
      oldseed <- NULL
    }
    set.seed(seed)
    if (is.null(A)) A <- apply(selectA(3, 3), c(1, 2), signif, digits = 2)
    if (is.null(B)) B <- apply(selectA(3, 3), c(1, 2), signif, digits = 2)

    if (!is.null(oldseed)) {
      .GlobalEnv$.Random.seed <- oldseed
    } else {
      rm(".Random.seed", envir = .GlobalEnv)
    }
  }

  # First objective - Branin
  c1 <- (x * 2 - 1) %*% A
  c1 <- (c1 + 1.45) / 2
  c2 <- c1[, 2]
  c3 <- c1[, 3]
  c1 <- c1[, 1]
  f2 <- (c2 - 5.1 * (c1 / (2 * pi))^2 + 5 / pi * c1 - 6)^2 + 10 * ((1 - 1 / (8 * pi)) * cos(c1) + 1) + sin(pi * c3)

  # Second objective (Currin)
  b1 <- (x * 2 - 1) %*% B
  b1 <- (b1 + 1.45) / 2
  b2 <- b1[, 2]
  b3 <- b1[, 3]
  b1 <- b1[, 1]
  f1 <- -sqrt((10.5 - b1) * (b1 + 5.5) * (b2 + 0.5)) - 1 / 30 * (b2 - 5.1 * (b1 / (2 * pi))^2 - 6)^2 - 1 / 3 * ((1 - 1 / (8 * pi)) * cos(b1) + 1) -
    cos(2 * pi * b3)

  return(cbind(f1, f2))
}
